/*
 * init.sql
 *
 * Creates the PostgreSQL table used by AppDbContext when the database container starts.
 * The unique name index supports the controller's one-record-per-subreddit behavior.
 */
CREATE TABLE IF NOT EXISTS "Subreddits" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Title" TEXT NOT NULL,
    "Description" TEXT NULL,
    "SubscriberCount" INTEGER NOT NULL,
    "ActiveAccountCount" INTEGER NULL,
    "CreatedUtc" TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Subreddits_Name" ON "Subreddits" ("Name");

CREATE TABLE IF NOT EXISTS "SubredditSnapshots" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SubredditId" INTEGER NOT NULL REFERENCES "Subreddits" ("Id") ON DELETE CASCADE,
    "SubscriberCount" INTEGER NOT NULL,
    "ActiveAccountCount" INTEGER NULL,
    "CapturedAtUtc" TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX IF NOT EXISTS "IX_SubredditSnapshots_SubredditId_CapturedAtUtc"
    ON "SubredditSnapshots" ("SubredditId", "CapturedAtUtc");
