CREATE TABLE IF NOT EXISTS "Subreddits" (
    "Id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "Name" TEXT NOT NULL,
    "Title" TEXT NOT NULL,
    "Description" TEXT NULL,
    "SubscriberCount" INTEGER NOT NULL,
    "ActiveAccountCount" INTEGER NOT NULL,
    "CreatedUtc" TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_Subreddits_Name" ON "Subreddits" ("Name");
